services:
  web:
    command: /bin/sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
      - /app/.venv

  tailwind:
    image: node:22-slim
    working_dir: /app
    command: /bin/sh -c "npm install --no-audit --no-fund && npm run tw"
    volumes:
      - .:/app
    tty: true