[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==6.0.1",
    "django-cotton>=2.6.2",
    "django-htmx==1.27.0",
    "gunicorn==24.1.1",
    "python-dotenv==1.2.1",
    "whitenoise[brotli]==6.11.0",
]
