# Generated by Django 6.0.1 on 2026-01-31 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workout_log.exercise'),
        ),
    ]
