# Generated by Django 6.0.1 on 2026-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0002_set_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(through='workout_log.ExerciseTagMap', to='workout_log.tag'),
        ),
    ]
