# Generated by Django 6.0.1 on 2026-01-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0003_exercise_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(related_name='exercises', through='workout_log.ExerciseTagMap', to='workout_log.tag'),
        ),
    ]
