# Generated by Django 6.0.1 on 2026-01-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0004_alter_exercise_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercisetagmap',
            constraint=models.UniqueConstraint(fields=('tag', 'exercise'), name='unique_exercise_tag'),
        ),
    ]
