# Generated by Django 6.0.1 on 2026-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0005_exercisetagmap_unique_exercise_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
