# Generated by Django 6.0.1 on 2026-02-17 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0006_alter_set_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(default='')),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='exercisetagmap',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='set',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='tag',
            name='highlighted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='set',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workout_log.session'),
        ),
    ]
