# Generated by Django 6.0.1 on 2026-02-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0007_session_exercisetagmap_active_set_notes_set_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisetagmap',
            name='active',
        ),
        migrations.AddField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_log.exercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_log.session'),
        ),
    ]
