# Generated by Django 6.0.1 on 2026-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0008_remove_exercisetagmap_active_exercise_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
