# Generated by Django 6.0.1 on 2026-03-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0009_alter_exercise_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_log.session'),
        ),
    ]
